### ISSUE TITLE
Mist sends invalid requests to SMTP mail server

### ISSUE THREAD

**Issue by davidrylance** [mistio/mist.io#1028]
Dear Mist maintainers,

Thank you for Mist. It's great!

I host my own e-mail server (postfix) and I noticed that after I create an account for Mist and configure Mist to use it, the server is literally flooded by requests that generate a lot of warning logs.

I was thinking maybe there is something wrong the mail server hosted on public internet so I installed Postfix into a container on private LAN and configured it with no authentication to relay e-mails to public mail server and I see the same error logs.

### Reproduce

Configure Mist e-mailing - in my case postfix on private LAN:
```
## Configure email settings.
MAILER_SETTINGS = {
    'mail.host': "192.168.1.25",
    'mail.port': "25",
    'mail.tls': False,
    'mail.starttls': False,
    'mail.username': "",
    'mail.password': "",
}
EMAIL_FROM = "existing@account.com"
```
Or to use mailserver on public internet
```
MAILER_SETTINGS = {
    'mail.host': "some.mailserver.com",
    'mail.port': "587",
    'mail.tls': True,
    'mail.starttls': True,
    'mail.username': "existing@account.com",
    'mail.password': "password",
}
EMAIL_FROM = "existing@account.com"
```
* Run Mist for the first time - no existing configuration
* Add user: `./bin/adduser --admin 'existing@account.com' --password ...`
* Login via web
* Add Cloud
* Watch the mail server and you'll see this:
~~~
Mar 17 08:34:11 32bd932f8e98 postfix/smtpd[111]: connect from unknown[IP removed]
Mar 17 08:34:11 32bd932f8e98 postfix/smtpd[111]: warning: Illegal address syntax from unknown[IP removed] in RCPT command: <>
Mar 17 08:34:16 32bd932f8e98 postfix/smtpd[113]: connect from unknown[IP removed]
Mar 17 08:34:16 32bd932f8e98 postfix/smtpd[111]: lost connection after RSET from unknown[IP removed]
Mar 17 08:34:16 32bd932f8e98 postfix/smtpd[111]: disconnect from unknown[IP removed] ehlo=1 mail=1 rcpt=0/1 rset=1 commands=3/4
Mar 17 08:34:16 32bd932f8e98 postfix/smtpd[113]: warning: Illegal address syntax from unknown[IP removed] in RCPT command: <>
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[111]: connect from unknown[IP removed]
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[113]: lost connection after RSET from unknown[IP removed]
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[113]: disconnect from unknown[IP removed] ehlo=1 mail=1 rcpt=0/1 rset=1 commands=3/4
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[111]: warning: Illegal address syntax from unknown[IP removed] in RCPT command: <>
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[111]: lost connection after RSET from unknown[IP removed]
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[111]: disconnect from unknown[IP removed] ehlo=1 mail=1 rcpt=0/1 rset=1 commands=3/4
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[113]: connect from unknown[IP removed]
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[111]: connect from unknown[IP removed]
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[114]: connect from unknown[IP removed]
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[115]: connect from unknown[IP removed]
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[116]: connect from unknown[IP removed]
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[113]: warning: Illegal address syntax from unknown[IP removed] in RCPT command: <>
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[117]: connect from unknown[IP removed]
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[111]: warning: Illegal address syntax from unknown[IP removed] in RCPT command: <>
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[114]: warning: Illegal address syntax from unknown[IP removed] in RCPT command: <>
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[115]: warning: Illegal address syntax from unknown[IP removed] in RCPT command: <>
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[116]: warning: Illegal address syntax from unknown[IP removed] in RCPT command: <>
Mar 17 08:34:21 32bd932f8e98 postfix/smtpd[117]: warning: Illegal address syntax from unknown[IP removed] in RCPT command: <>
~~~

* These logs starts after the first cloud is added.

Btw. e-mails work - I tested adding rule to mail myself when a VM is stopped / started and I get e-mails. It just something else Mist does that is wrong.

Thank you.

Kind regards,

David

**Comment by dimgal1** [comment]
Hi @davidrylance we looked into this and it seems there are several issues leading to the problem.

- By default Mist will query for some metrics the Victoria Metrics containers which are not included by default on `docker-compose.yml`.
- Mist will try to send an email alert to a group (that should be configured in `settings.py`)  that the metrics are inaccessible. If the email group is not configured an empty email address is passed likely causing the `Illegal address syntax from unknown` warning you posted.

To alleviate these issues:
- Add a `docker-compose.override.yml` file on Mist installation folder with the following:
```
  vminsert:
    image: victoriametrics/vminsert:v1.60.0-cluster
    command:
      - '--influxTrimTimestamp=1s'
      - '--storageNode=vmstorage:8400'
    ports:
      - 8480

  vmstorage:
    image: victoriametrics/vmstorage:v1.60.0-cluster
    command:
      - '--retentionPeriod=12'
      - '--storageDataPath=/var/lib/victoria-metrics-data'
    ports:
      - 8400
      - 8401
      - 8482
    volumes:
      - victoria-metrics:/var/lib/victoria-metrics-data

  vmselect:
    image: victoriametrics/vmselect:v1.60.0-cluster
    command:
      - '--search.latencyOffset=0s'
      - '--search.cacheTimestampOffset=15m'
      - '--storageNode=vmstorage:8401'
      - '--search.maxQueryLen=1GiB'
    ports:
      - 8481
```
- Add the following to `settings.py` file and update the email addresses:
```
NOTIFICATION_EMAIL = {
    'all': "existing@account.com",
    'dev': "existing@account.com",
    'ops': "existing@account.com",
    'sales': "existing@account.com",
    'demo': "existing@account.com",
    'support': "existing@account.com",
}
```
Thanks for bringing this up to our attention. These issues will be fixed on our next release!
