### ISSUE TITLE
Docker is not working 

### ISSUE THREAD

**Issue by tsanyqudsi** [mistio/mist.io#656]
Hi, 

apparently i'm having a problem with Docker installation of Mist.io, i did the installation procedure on http://docs.mist.io/article/39-installation but it seems that i'm having the same problem with https://github.com/mistio/mist.io/issues/342

mind telling me where did i go wrong ?

**Comment by mgogoulos** [comment]
Hi, 
there's an issue with the mist.io docker image and we need a few more days to check it out. I will inform you once this is done.

Sorry for the trouble, 
Markos

**Comment by tsanyqudsi** [comment]
Will do :) thanks for the feedback

Sent From Sony Z1 Compact

**Comment by gisjedi** [comment]
There are issues with the way RabbitMQ is configured within the image.  It endlessly loops attempting to start. I was able to just get up and running by linking in a clean RabbitMQ container from Docker Hub and updating the appropriate settings.

If you place the docker-compose.yml and settings.py below into a directory and run the following command you should be up and running:

```
docker-compose up -d
```

## docker-compose.yml

```
mist:
  image: mist/mistio
  ports:
  - 8000:8000
  volumes:
  - ./settings.py:/home/mist/mist.io/settings.py
  environment:
  - BRANCH=staging
  links:
  - rabbitmq
rabbitmq:
  image: rabbitmq
```

## settings.py

```
JS_BUILD = True
CSS_BUILD = True
SSL_VERIFY = False
AMQP_URI='rabbitmq:5672'
BROKER_URL='amqp://guest:guest@rabbitmq:5672/'
```
